/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package co.unicauca.presentation;

import static co.unicauca.presentation.GUIDocenteFrame.userRepository;
import co.unicauca.solid.access.Factory;
import co.unicauca.solid.access.FilePGRepository;
import co.unicauca.solid.access.IProyectoGradoRepository;
import co.unicauca.solid.access.IUserRepository;
import co.unicauca.solid.domain.FilePG;
import co.unicauca.solid.domain.ProyectoGrado;
import co.unicauca.solid.service.FilePGService;
import co.unicauca.solid.service.ProyectoGradoService;
import co.unicauca.solid.service.UserService;
import co.unicauca.utilities.exeption.InvalidUserDataException;
import co.unicauca.utilities.exeption.UserNotFoundException;
import java.awt.FileDialog;
import java.awt.Frame;
import java.io.File;
import java.io.FilenameFilter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import co.unicauca.solid.access.IFilePGRepository;

/**
 *
 * @author crist
 */
public class JFormProyectoGrado extends javax.swing.JFrame {

    IFilePGRepository formatoARepository = Factory.getInstance().getFileRepository("default");
    IProyectoGradoRepository proyectoRepository = Factory.getInstance().getProyectoGradoRepository("default");
    IUserRepository userRepository = Factory.getInstance().getUserRepository("default");
    UserService userService = new UserService(userRepository);
    ProyectoGradoService proyectoService = new ProyectoGradoService(proyectoRepository, userService);
    FilePGService formatoAService = new FilePGService(formatoARepository, proyectoService); // Inyección de dependencias corregida
    FilePG formatoA;

    /**
     * Creates new form JFormProyectoGrado
     */
    public JFormProyectoGrado() {
        setTitle("nuevo proyecto");
        this.setLocationRelativeTo(null);
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAbjPdf = new javax.swing.JButton();
        btnAbjCartLab = new javax.swing.JButton();
        btnEnviar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtTituloP = new javax.swing.JTextField();
        txtDirector = new javax.swing.JTextField();
        txtCoodirector = new javax.swing.JTextField();
        txtObjGeneral = new javax.swing.JTextField();
        txtObjespecifico = new javax.swing.JTextField();
        combModalidad = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtEstudiante = new javax.swing.JTextField();
        txtSelectPdf = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Titulo Proyecto de Grado");

        jLabel2.setText("modalidad");

        jLabel3.setText("Director");

        jLabel4.setText("Coodirector");

        jLabel5.setText("Objetivo General");

        jLabel6.setText("Objetivo especifico");

        btnAbjPdf.setText("Abjuntar Formato A");
        btnAbjPdf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAbjPdfMouseClicked(evt);
            }
        });

        btnAbjCartLab.setText("Abjuntar carta laboral");

        btnEnviar.setText("enviar");
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtTituloP.setText("jTextField1");

        txtDirector.setText("jTextField2");

        txtCoodirector.setText("jTextField3");

        txtObjGeneral.setText("jTextField4");

        txtObjespecifico.setText("jTextField5");

        combModalidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "INVESTIGACION", "PRACTICA_PROFESIONAL" }));

        jLabel7.setText("Correo del estudiante");

        txtEstudiante.setText("txtEstudiante");

        txtSelectPdf.setText("sin atchivo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtTituloP))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(26, 26, 26)
                                .addComponent(txtCoodirector))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(31, 31, 31)
                                .addComponent(txtObjGeneral)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEnviar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnCancelar))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDirector)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(combModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(21, 21, 21))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAbjPdf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                        .addComponent(btnAbjCartLab)
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtObjespecifico))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtEstudiante)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(txtSelectPdf)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTituloP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combModalidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtCoodirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEstudiante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtObjGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(84, 84, 84)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtObjespecifico, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(72, 72, 72)
                        .addComponent(txtSelectPdf)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbjPdf)
                    .addComponent(btnAbjCartLab))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEnviar)
                    .addComponent(btnCancelar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
        if (formatoA == null) {
            JOptionPane.showMessageDialog(this,
                    "Error: Debe cargar el Formato A (PDF) antes de enviar el proyecto",
                    "Documento requerido",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {

            // Crear nuevo proyecto con los campos actualizados
            ProyectoGrado proyecto = new ProyectoGrado();
            proyecto.setTitulo(txtTituloP.getText());
            proyecto.setModalidad(combModalidad.getSelectedItem().toString());
            proyecto.setDirectorEmail(txtDirector.getText());
            proyecto.setCodirectorEmail(txtCoodirector.getText().isEmpty() ? null : txtCoodirector.getText());
            proyecto.setEstudianteEmail(txtEstudiante.getText());
            proyecto.setObjetivoGeneral(txtObjGeneral.getText());
            proyecto.setObjetivosEspecificos(txtObjespecifico.getText());
            proyecto.setEstadoActual("EN_PRIMERA_EVALUACION_FORMATO_A");
            proyecto.setNumeroIntento(1);
            proyecto.setFechaCreacion(LocalDateTime.now());
            proyecto.setFechaUltimaActualizacion(LocalDateTime.now());
            proyecto.setRechazadoDefinitivamente('N');
            proyecto.setObservacionesEvaluacion(null); // Nuevo campo

            int idProyecto = proyectoService.crearProyecto(proyecto);
            System.out.println("Proyecto creado con ID: " + idProyecto);

            if (idProyecto != -1) {
                // Crear un NUEVO objeto FilePG con los campos actualizados
                FilePG nuevoFormatoA = new FilePG();
                nuevoFormatoA.setIdProyecto(idProyecto);
                nuevoFormatoA.setTipoDocumento("FORMATO_A");
                nuevoFormatoA.setVersion(1);
                nuevoFormatoA.setContenido(formatoA.getContenido());
                nuevoFormatoA.setNombreArchivo(formatoA.getNombreArchivo());

                // Extraer extensión del nombre del archivo
                String nombreArchivo = formatoA.getNombreArchivo();
                String extension = "";
                int ultimoPunto = nombreArchivo.lastIndexOf('.');
                if (ultimoPunto > 0) {
                    extension = nombreArchivo.substring(ultimoPunto + 1);
                }
                nuevoFormatoA.setExtension(extension);

                // Tamaño del contenido
                nuevoFormatoA.setTamaño((long) formatoA.getContenido().length);
                nuevoFormatoA.setFechaSubida(LocalDateTime.now());
                nuevoFormatoA.setEstado("PENDIENTE");
                nuevoFormatoA.setObservaciones(null);

                // Usar el nuevo método específico para subir Formato A
                int id = formatoAService.subirFormatoA(idProyecto,
                        nuevoFormatoA.getContenido(),
                        nuevoFormatoA.getNombreArchivo());

                if (id != -1) {
                    JOptionPane.showMessageDialog(this,
                            "PDF guardado en base de datos con ID: " + id
                            + "\nTamaño: " + nuevoFormatoA.getContenido().length + " bytes"
                            + "\nNombre: " + formatoA.getNombreArchivo()
                            + "\nTipo: " + nuevoFormatoA.getTipoDocumento());

                    // Opcional: Obtener documentos del proyecto para verificar
                    System.out.println("\nDocumentos del proyecto " + idProyecto + ":");
                    try {
                        List<FilePG> documentos = formatoAService.obtenerDocumentosPorProyecto(idProyecto);
                        documentos.forEach(doc -> {
                            System.out.println("- ID: " + doc.getIdDocumento()
                                    + ", Tipo: " + doc.getTipoDocumento()
                                    + ", Archivo: " + doc.getNombreArchivo());
                        });
                    } catch (UserNotFoundException | InvalidUserDataException e) {
                        System.out.println("No se pudieron obtener los documentos: " + e.getMessage());
                    }

                    this.dispose();
                } else {
                    JOptionPane.showMessageDialog(this, "Error al guardar el PDF en la base de datos");
                }
            }
        } catch (InvalidUserDataException e) {
            JOptionPane.showMessageDialog(this,
                    "Error de validación: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (UserNotFoundException e) {
            JOptionPane.showMessageDialog(this,
                    "Usuario no encontrado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error inesperado: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnEnviarMouseClicked

    private void btnAbjPdfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAbjPdfMouseClicked
        FileDialog fileDialog = new FileDialog((Frame) null, "Seleccionar archivo PDF", FileDialog.LOAD);
        fileDialog.setFilenameFilter(new FilenameFilter() {
            public boolean accept(File dir, String name) {
                return name.toLowerCase().endsWith(".pdf");
            }
        });
        fileDialog.setVisible(true);

        String selectedDirectory = fileDialog.getDirectory();
        String selectedFileName = fileDialog.getFile();

        if (selectedDirectory != null && selectedFileName != null) {
            String rutaPDF = selectedDirectory + selectedFileName;

            try {
                // Leer archivo PDF
                byte[] contenidoPDF = Files.readAllBytes(Paths.get(rutaPDF));
                String nombreArchivo = selectedFileName; // Usar el nombre real del archivo

                // Crear objeto FilePG temporal solo con los datos básicos necesarios
                formatoA = new FilePG();
                formatoA.setIdProyecto(null); // Se asignará después cuando se cree el proyecto
                formatoA.setTipoDocumento("FORMATO_A");
                formatoA.setVersion(1);
                formatoA.setContenido(contenidoPDF);
                formatoA.setNombreArchivo(nombreArchivo);

                // Extraer extensión
                String extension = "";
                int ultimoPunto = nombreArchivo.lastIndexOf('.');
                if (ultimoPunto > 0) {
                    extension = nombreArchivo.substring(ultimoPunto + 1);
                }
                formatoA.setExtension(extension);

                formatoA.setTamaño((long) contenidoPDF.length);
                formatoA.setFechaSubida(LocalDateTime.now());
                formatoA.setEstado("PENDIENTE");
                formatoA.setObservaciones(null);

                // Actualizar la etiqueta con el nombre real del archivo
                txtSelectPdf.setText(nombreArchivo);

                System.out.println("Archivo cargado: " + nombreArchivo
                        + " (" + contenidoPDF.length + " bytes)");

            } catch (IOException e) {
                JOptionPane.showMessageDialog(this,
                        "Error al leer el archivo: " + e.getMessage());
                e.printStackTrace();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this,
                        "Error inesperado: " + e.getMessage());
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnAbjPdfMouseClicked

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFormProyectoGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFormProyectoGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFormProyectoGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFormProyectoGrado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFormProyectoGrado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbjCartLab;
    private javax.swing.JButton btnAbjPdf;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JComboBox<String> combModalidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField txtCoodirector;
    private javax.swing.JTextField txtDirector;
    private javax.swing.JTextField txtEstudiante;
    private javax.swing.JTextField txtObjGeneral;
    private javax.swing.JTextField txtObjespecifico;
    private javax.swing.JLabel txtSelectPdf;
    private javax.swing.JTextField txtTituloP;
    // End of variables declaration//GEN-END:variables
}
